

```{r}
setwd(here::here('35_Jul_05_2023'))
```


```{r}
library(tidyverse)
penguins_data <- palmerpenguins::penguins |> 
  filter(!is.na(sex)) 

penguins_plot <- penguins_data |> 
  ggplot(aes(x = body_mass_g, fill = species)) +
  geom_histogram(position = 'identity', alpha = 0.7) +
  theme_minimal(base_size = 16) +
  scale_fill_manual(values = thematic::okabe_ito(3)) 
penguins_plot
```


```{r}
penguins_plot +
  facet_wrap(vars(species))
```


```{r}
library(gghighlight)
penguins_plot +
  facet_wrap(vars(species)) +
  gghighlight()
```

```{r}
penguins_plot +
  facet_wrap(vars(species)) +
  gghighlight(body_mass_g >= 3500)
```


```{r}
# Original data from https://ourworldindata.org/time-with-others-lifetime
basic_line_chart <- read_csv('owd_data_cleaned.csv') |> 
  ggplot(aes(x = age, y = minutes, color = person)) +
  geom_line(linewidth = 1.5) +
  theme_minimal(base_size = 16) +
  labs(
    x = 'Age',
    y = element_blank(),
    title = 'Around the age of 40, we spend less time with children\nand more time alone',
    subtitle = 'Daily time spent with others (in minutes)',
    caption = 'Data: Our World in Data'
  ) +
  scale_color_manual(values = thematic::okabe_ito(6))
basic_line_chart
```



```{r}
# Code for line chart on GitHub
basic_line_chart +
  gghighlight(
    person %in% c('alone', 'children'), 
    age >= 38
  )
```


```{r}
basic_line_chart +
  gghighlight(
    person %in% c('alone', 'children'), 
    age >= 38, 
    use_direct_label = FALSE,
    use_group_by = FALSE
  )
```


```{r}
basic_line_chart +
  gghighlight(
    person %in% c('alone', 'children'), 
    age >= 38, 
    use_direct_label = FALSE,
    use_group_by = FALSE,
    unhighlighted_params = list(color = 'grey70', linewidth = 1)
  )
```



