


```{r}
library(tidyverse)

penguins <- palmerpenguins::penguins |> 
  filter(!is.na(sex))

colors <- thematic::okabe_ito(3)
# Set names to species so that scale_fill_manual() will use these colors
names(colors) <- unique(penguins$species)

basic_plot <- penguins |> 
  ggplot(aes(x = bill_length_mm, y = body_mass_g, fill = species)) +
  geom_point(shape = 21, size = 5, alpha = 0.85, color = 'grey10') +
  theme_minimal(base_size = 16, base_family = 'Source Sans Pro') +
  scale_fill_manual(values = colors) +
  labs(
    x = 'Bill length (in mm)',
    y = element_blank(),
    title = 'Penguins from the Palmer Archipelago',
    subtitle = 'Penguin weights (in g) for the Species Adelie, Chinstrap and Gentoo'  
  ) +
  theme(
    plot.title.position = 'plot',
    text = element_text(color = 'grey20'),
    axis.text = element_text(color = 'grey30'),
    plot.title = element_text(family = 'Merriweather', size = 26, margin = margin(b = 7, unit = 'mm')),
    plot.subtitle = element_text(size = 18, lineheight = 1.3),
    panel.background = element_rect(color = 'grey90'),
    panel.grid.major = element_line(color = 'grey90'),
    panel.grid.minor = element_blank()
  )
basic_plot
```

Add span-tags

```{r}
basic_plot +
  labs(
    subtitle = 'Penguin weights (in g) for the Species <span>Adelie</span>, <span>Chinstrap</span> and <span>Gentoo</span>'
  )
```

Enable HTML rendering

```{r}
basic_plot +
  labs(
    subtitle = 'Penguin weights (in g) for the Species <span>Adelie</span>, <span>Chinstrap</span> and <span>Gentoo</span>'
  ) +
  theme(
    plot.subtitle = ggtext::element_markdown(size = 18, lineheight = 1.3)
  )
```


Colored text

```{r}
basic_plot +
  labs(
    subtitle = 'Penguin weights (in g) for the Species <span style = "color:#E69F00">Adelie</span>, <span style = "color:#0072B2">Chinstrap</span> and <span style = "color:#009E73">Gentoo</span>'
  ) +
  theme(
    plot.subtitle = ggtext::element_markdown(size = 18, lineheight = 1.3),
    # Remove legend as not needed anymore
    legend.position = 'none'
  )
```

Bold text

```{r}
basic_plot +
  labs(
    subtitle = 'Penguin weights (in g) for the Species <span style = "color:#E69F00">**Adelie**</span>, <span style = "color:#0072B2">**Chinstrap**</span> and <span style = "color:#009E73">**Gentoo**</span>'
  ) +
  theme(
    plot.subtitle = ggtext::element_markdown(size = 18, lineheight = 1.3),
    # Remove legend as not needed anymore
    legend.position = 'none'
  )
```

Full code (also using `glue()`)

```{r}
# I've also use the Markdown notation **...** to make the words a bit bold
title_text <- glue::glue(
  'Penguin weights (in g) for the Species',  
  '<span style = "color:{colors["Adelie"]}">**Adelie**</span>,', 
  '<span style = "color:{colors["Chinstrap"]}">**Chinstrap**</span>', 
  'and',
  '<span style = "color:{colors["Gentoo"]}">**Gentoo**</span>', 
  .sep = ' '
)

penguins |> 
  ggplot(aes(x = bill_length_mm, y = body_mass_g, fill = species)) +
  geom_point(shape = 21, size = 5, alpha = 0.85, color = 'grey10') +
  theme_minimal(base_size = 16, base_family = 'Source Sans Pro') +
  scale_fill_manual(values = colors) +
  labs(
    x = 'Bill length (in mm)',
    y = element_blank(),
    title = 'Penguins from the Palmer Archipelago',
    subtitle = title_text
  ) +
  theme(
    plot.title.position = 'plot',
    text = element_text(color = 'grey20'),
    axis.text = element_text(color = 'grey30'),
    plot.title = element_text(family = 'Merriweather', size = 26, margin = margin(b = 7, unit = 'mm')),
    plot.subtitle = ggtext::element_markdown(size = 18, lineheight = 1.3),
    panel.background = element_rect(color = 'grey90'),
    panel.grid.major = element_line(color = 'grey90'),
    panel.grid.minor = element_blank(),
    legend.position = 'none'
  )
```



