---
theme: ../theme.scss
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
knitr: 
  opts_chunk: 
    collapse: true
---

```{r}
setwd(here::here('63_Feb_07_2024'))
library(tidyverse)

theme_set(
  theme_minimal(
    base_size = 16,
    base_family = 'Source Sans Pro'
  ) +
    theme(panel.grid.minor = element_blank())
) 
```


```{.r}
GEOCODE_API_KEY=123
SOME_OTHER_KEY=34653462542
```



```{r}
#| eval: false
library(tidyverse)
library(httr2)
dotenv::load_dot_env()

geocode_base_url <- 'https://maps.googleapis.com/maps/api/geocode/json'
response <- request(geocode_base_url) |> 
  req_url_query(
    address = '1900 E Kenwood Blvd, Milwaukee, WI 53211, USA',
    key = Sys.getenv('GEOCODE_API_KEY')
  ) |>
  req_perform()
```


```{r}
library(tidyverse)
library(httr2)
dotenv::load_dot_env(file = '../.env')

geocode_base_url <- 'https://maps.googleapis.com/maps/api/geocode/json'
response <- request(geocode_base_url) |> 
  req_url_query(
    address = '1900 E Kenwood Blvd, Milwaukee, WI 53211, USA',
    key = Sys.getenv('GEOCODE_API_KEY')
  ) |>
  req_perform()
response
```


```{r}
response |> 
  resp_body_json() |> 
  glimpse()
```


```{r}
library(tidyverse)
library(httr2)
dotenv::load_dot_env(file = '../.env') # Load .env file into environment
geocode_base_url <- 'https://maps.googleapis.com/maps/api/geocode/json'

# Make API Request
response <- request(geocode_base_url) |> 
  req_url_query(
    address = '1900 E Kenwood Blvd, Milwaukee, WI 53211, USA',
    key = Sys.getenv('GEOCODE_API_KEY') # Access API key from environment
  ) |>
  req_perform()

# Extract coordinates from response
response |> 
  resp_body_json() |> 
  pluck('results', 1, 'geometry', 'location')  |> 
  unlist()
```

