---
theme: ../theme.scss
format: 
  html: 
    fig-height: 5
    fig-dpi: 300
    fig-width: 8.88
    fig-align: center
knitr: 
  opts_chunk: 
    collapse: true
---

```{r}
setwd(here::here("71_Apr_03_2024"))
library(tidyverse)
```



```{r}
library(htmltools)
tags$select(
  tags$option("Chicago, IL"),
  tags$option("Milwaukee, WI")
) |> browsable()
```


```{r}
tags$select(
  tags$option(value = "Chicago_IL", "Chicago, IL"),
  tags$option(value = "Milwaukee_WI", "Milwaukee, WI")
) |> browsable()
```


```{r}
create_dropdown_entry <- function(cityname) {
  tags$option(
    value = cityname |>
      str_replace_all(" ", "_") |>
      str_replace_all(",", ""),
    cityname
  )
}
```


```{r}
tags$select(
  map(
    c(
      "Chicago, IL",
      "Milwaukee, WI",
      "New York City, NY", 
      "Los Angeles, CA", 
      "San Francisco, CA"
    ) |> sort(),
    create_dropdown_entry
  )
) |> browsable()
```


```{r}
tags$select(
  onchange = 'alert("You selected a city!")',
  map(
    c(
      "Chicago, IL",
      "Milwaukee, WI",
      "New York City, NY", 
      "Los Angeles, CA", 
      "San Francisco, CA"
    ) |> sort(),
    create_dropdown_entry
  )
) |> browsable()
```


```{r}
dropdown_menu <- tags$select(
  id = "dropdown_location",
  onchange = 'alert(document.getElementById("dropdown_location").value)',
  map(
    c(
      "Chicago, IL",
      "Milwaukee, WI",
      "New York City, NY", 
      "Los Angeles, CA", 
      "San Francisco, CA"
    ) |> sort(),
    create_dropdown_entry
  )
) 

dropdown_menu |> browsable()

```



```{r}
one_day_row <- function(icon = "cloud-rain", day = "Today", temps = "22°/14°") {
  div(
    div(
      shiny::icon(
        icon,
        style = "margin-right: 10px; vertical-align: middle"
      ),
      span(
        day,
        style = "margin-right: 25px"
      ),
    ),
    div(
      temps,
    ),
    style = htmltools::css(
      font_size = "20px",
      font_weight = 600,
      margin_top = "5px",
      display = "flex",
      justify_content = "space-between"
    )
  )
}
```


```{r}
library(htmltools)
div(
  div(
    "11:38",
    div(
      shiny::icon(
        "signal",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "wifi",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "battery-three-quarters",
        style = "margin-left: 5px"
      )
    ),
    style = htmltools::css(
      display = "flex",
      justify_content = "space-between",
      font_size = "20px",
      font_weight = 600,
      margin_bottom = "30px"
    ),
    id = "top-bar"
  ),
  div(
    style = htmltools::css(
      font_size = "42px",
      font_weight = 600
    ),
    id = "location-container",
    shiny::icon(
      "location-dot",
      style = "font-size:40px"
    ),
    dropdown_menu,
  ),
  div(
    span(
      "22°",
      style = htmltools::css(
        font_size = "100px",
        font_weight = 600,
      )
    ),
    span(
      "Rain",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    span(
      "22°/14°",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    id = "temp-container"
  ),
  shiny::icon(
    "cloud-rain",
    style = htmltools::css(
      font_size = "150px",
      margin_top = "35px",
      margin_right = "auto",
      margin_left = "auto"
    )
  ),
  div(
    div( ### <- Changes here
      one_day_row(),
      one_day_row("sun", "Tomorrow", "23°/15°"),
      one_day_row("sun", "Monday", "23°/15°"),
      style = "margin: 20px"
    ),
    div(
      shiny::icon("circle", class = "fa-solid"),
      shiny::icon("circle"),
      shiny::icon("circle"),
      style = htmltools::css(
        margin_bottom = "5px",
        font_size = "10px",
        margin_right = "auto",
        margin_left = "auto"
      )
    ),
    style = htmltools::css(
      background = "linear-gradient(45deg, #7dc8ff, #7dcafe)",
      border_radius = "10px",
      margin_top = "50px",
      font_family = "Source Sans Pro",
      color = "white",
      margin_left = "30px",
      margin_right = "30px",
      display = "flex", ### <- Changes here
      flex_direction = "column" ### <- Changes here
    ),
    id = "next-3-days-container"
  ),
  style = htmltools::css(
    width = "375px",
    height = "650px",
    background = "linear-gradient(45deg, #46afff, #47c8ff)",
    border = "3px solid #333333",
    border_radius = "20px",
    padding = "15px 25px 15px 25px",
    font_family = "Source Sans Pro",
    color = "white",
    display = "flex",
    flex_direction = "column"
  ),
  id = "phone-container"
) |>
  div(
    br(),
    style = "all: initial;"
  ) |>
  browsable()
```


```{r}
dropdown_menu <- tags$select(
  id = "dropdown_location",
  style = css(
    background = "transparent",   ## Changes here
    border = 'none'               ## Changes here
  ),
  onchange = 'alert(document.getElementById("dropdown_location").value)',
  map(
    c(
      "Chicago, IL",
      "Milwaukee, WI",
      "New York City, NY", 
      "Los Angeles, CA", 
      "San Francisco, CA"
    ) |> sort(),
    create_dropdown_entry
  )
) 
```


```{r}
library(htmltools)
div(
  div(
    "11:38",
    div(
      shiny::icon(
        "signal",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "wifi",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "battery-three-quarters",
        style = "margin-left: 5px"
      )
    ),
    style = htmltools::css(
      display = "flex",
      justify_content = "space-between",
      font_size = "20px",
      font_weight = 600,
      margin_bottom = "30px"
    ),
    id = "top-bar"
  ),
  div(
    style = htmltools::css(
      font_size = "42px",
      font_weight = 600
    ),
    id = "location-container",
    shiny::icon(
      "location-dot",
      style = "font-size:40px"
    ),
    dropdown_menu,
  ),
  div(
    span(
      "22°",
      style = htmltools::css(
        font_size = "100px",
        font_weight = 600,
      )
    ),
    span(
      "Rain",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    span(
      "22°/14°",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    id = "temp-container"
  ),
  shiny::icon(
    "cloud-rain",
    style = htmltools::css(
      font_size = "150px",
      margin_top = "35px",
      margin_right = "auto",
      margin_left = "auto"
    )
  ),
  div(
    div( ### <- Changes here
      one_day_row(),
      one_day_row("sun", "Tomorrow", "23°/15°"),
      one_day_row("sun", "Monday", "23°/15°"),
      style = "margin: 20px"
    ),
    div(
      shiny::icon("circle", class = "fa-solid"),
      shiny::icon("circle"),
      shiny::icon("circle"),
      style = htmltools::css(
        margin_bottom = "5px",
        font_size = "10px",
        margin_right = "auto",
        margin_left = "auto"
      )
    ),
    style = htmltools::css(
      background = "linear-gradient(45deg, #7dc8ff, #7dcafe)",
      border_radius = "10px",
      margin_top = "50px",
      font_family = "Source Sans Pro",
      color = "white",
      margin_left = "30px",
      margin_right = "30px",
      display = "flex", ### <- Changes here
      flex_direction = "column" ### <- Changes here
    ),
    id = "next-3-days-container"
  ),
  style = htmltools::css(
    width = "375px",
    height = "650px",
    background = "linear-gradient(45deg, #46afff, #47c8ff)",
    border = "3px solid #333333",
    border_radius = "20px",
    padding = "15px 25px 15px 25px",
    font_family = "Source Sans Pro",
    color = "white",
    display = "flex",
    flex_direction = "column"
  ),
  id = "phone-container"
) |>
  div(
    br(),
    style = "all: initial;"
  ) |>
  browsable()
```


```{r}
dropdown_menu <- tags$select(
  style = css(
    background = "transparent",
    border = "none",
    font_size = "42px",                ## Changes here
    font_weight = 600,                 ## Changes here
    font_family = "Source Sans Pro",   ## Changes here
    color = "white"                    ## Changes here
  ),
  id = "dropdown_location",
  onchange = 'alert(document.getElementById("dropdown_location").value)',
  map(
    c("Chicago, IL", "Milwaukee, WI", 
      "New York City, NY", "Los Angeles, CA", 
      "San Francisco, CA") |> sort(),
    create_dropdown_entry
  )
)
```



```{r}
library(htmltools)
div(
  div(
    "11:38",
    div(
      shiny::icon(
        "signal",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "wifi",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "battery-three-quarters",
        style = "margin-left: 5px"
      )
    ),
    style = htmltools::css(
      display = "flex",
      justify_content = "space-between",
      font_size = "20px",
      font_weight = 600,
      margin_bottom = "30px"
    ),
    id = "top-bar"
  ),
  div(
    style = htmltools::css(
      font_size = "42px",
      font_weight = 600
    ),
    id = "location-container",
    shiny::icon(
      "location-dot",
      style = "font-size:40px"
    ),
    dropdown_menu,
  ),
  div(
    span(
      "22°",
      style = htmltools::css(
        font_size = "100px",
        font_weight = 600,
      )
    ),
    span(
      "Rain",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    span(
      "22°/14°",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    id = "temp-container"
  ),
  shiny::icon(
    "cloud-rain",
    style = htmltools::css(
      font_size = "150px",
      margin_top = "35px",
      margin_right = "auto",
      margin_left = "auto"
    )
  ),
  div(
    div( ### <- Changes here
      one_day_row(),
      one_day_row("sun", "Tomorrow", "23°/15°"),
      one_day_row("sun", "Monday", "23°/15°"),
      style = "margin: 20px"
    ),
    div(
      shiny::icon("circle", class = "fa-solid"),
      shiny::icon("circle"),
      shiny::icon("circle"),
      style = htmltools::css(
        margin_bottom = "5px",
        font_size = "10px",
        margin_right = "auto",
        margin_left = "auto"
      )
    ),
    style = htmltools::css(
      background = "linear-gradient(45deg, #7dc8ff, #7dcafe)",
      border_radius = "10px",
      margin_top = "50px",
      font_family = "Source Sans Pro",
      color = "white",
      margin_left = "30px",
      margin_right = "30px",
      display = "flex", ### <- Changes here
      flex_direction = "column" ### <- Changes here
    ),
    id = "next-3-days-container"
  ),
  style = htmltools::css(
    width = "375px",
    height = "650px",
    background = "linear-gradient(45deg, #46afff, #47c8ff)",
    border = "3px solid #333333",
    border_radius = "20px",
    padding = "15px 25px 15px 25px",
    font_family = "Source Sans Pro",
    color = "white",
    display = "flex",
    flex_direction = "column"
  ),
  id = "phone-container"
) |>
  div(
    br(),
    style = "all: initial;"
  ) |>
  browsable()
```

```{r}
create_dropdown_entry <- function(cityname) {
  tags$option(
    style = css(
      background_color = "#46c1ff"
    ),
    value = cityname |>
      str_replace_all(" ", "_") |>
      str_replace_all(",", ""),
    cityname
  )
}
```


```{r}
dropdown_menu <- tags$select(
  style = css(
    background = "transparent",
    border = "none",
    font_size = "42px",              
    font_weight = 600,               
    font_family = "Source Sans Pro", 
    color = "white"                  
  ),
  id = "dropdown_location",
  onchange = 'alert(document.getElementById("dropdown_location").value)',
  map(
    c("Chicago, IL", "Milwaukee, WI", 
      "New York City, NY", "Los Angeles, CA", 
      "San Francisco, CA") |> sort(),
    create_dropdown_entry
  )
)
```


```{r}
library(htmltools)
div(
  div(
    "11:38",
    div(
      shiny::icon(
        "signal",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "wifi",
        style = "margin-left: 5px"
      ),
      shiny::icon(
        "battery-three-quarters",
        style = "margin-left: 5px"
      )
    ),
    style = htmltools::css(
      display = "flex",
      justify_content = "space-between",
      font_size = "20px",
      font_weight = 600,
      margin_bottom = "30px"
    ),
    id = "top-bar"
  ),
  div(
    style = htmltools::css(
      font_size = "42px",
      font_weight = 600
    ),
    id = "location-container",
    shiny::icon(
      "location-dot",
      style = "font-size:40px"
    ),
    dropdown_menu,
  ),
  div(
    span(
      "22°",
      style = htmltools::css(
        font_size = "100px",
        font_weight = 600,
      )
    ),
    span(
      "Rain",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    span(
      "22°/14°",
      style = htmltools::css(
        font_size = "25px",
        margin_left = "10px"
      )
    ),
    id = "temp-container"
  ),
  shiny::icon(
    "cloud-rain",
    style = htmltools::css(
      font_size = "150px",
      margin_top = "35px",
      margin_right = "auto",
      margin_left = "auto"
    )
  ),
  div(
    div( ### <- Changes here
      one_day_row(),
      one_day_row("sun", "Tomorrow", "23°/15°"),
      one_day_row("sun", "Monday", "23°/15°"),
      style = "margin: 20px"
    ),
    div(
      shiny::icon("circle", class = "fa-solid"),
      shiny::icon("circle"),
      shiny::icon("circle"),
      style = htmltools::css(
        margin_bottom = "5px",
        font_size = "10px",
        margin_right = "auto",
        margin_left = "auto"
      )
    ),
    style = htmltools::css(
      background = "linear-gradient(45deg, #7dc8ff, #7dcafe)",
      border_radius = "10px",
      margin_top = "50px",
      font_family = "Source Sans Pro",
      color = "white",
      margin_left = "30px",
      margin_right = "30px",
      display = "flex", ### <- Changes here
      flex_direction = "column" ### <- Changes here
    ),
    id = "next-3-days-container"
  ),
  style = htmltools::css(
    width = "375px",
    height = "650px",
    background = "linear-gradient(45deg, #46afff, #47c8ff)",
    border = "3px solid #333333",
    border_radius = "20px",
    padding = "15px 25px 15px 25px",
    font_family = "Source Sans Pro",
    color = "white",
    display = "flex",
    flex_direction = "column"
  ),
  id = "phone-container"
) |>
  div(
    br(),
    style = "all: initial;"
  ) |>
  browsable()
```


