```{r}
library(tidyverse)

penguins <- palmerpenguins::penguins |> 
  filter(!is.na(sex))

colors <- thematic::okabe_ito(3)
# Set names to species so that scale_fill_manual() will use these colors
names(colors) <- unique(penguins$species)
title_text <- glue::glue(
  'Penguin weights (in g) for the Species',  
  '<span style = "color:{colors["Adelie"]}">**Adelie**</span>,', 
  '<span style = "color:{colors["Chinstrap"]}">**Chinstrap**</span>', 
  'and',
  '<span style = "color:{colors["Gentoo"]}">**Gentoo**</span>', 
  .sep = ' '
)

penguins |> 
  ggplot(aes(x = bill_length_mm, y = body_mass_g, fill = species)) +
  geom_point(shape = 21, size = 5, alpha = 0.85, color = 'grey10') +
  theme_minimal(base_size = 16, base_family = 'Source Sans Pro') +
  scale_fill_manual(values = colors) +
  labs(
    x = 'Bill length (in mm)',
    y = element_blank(),
    title = 'Penguins from the Palmer Archipelago',
    subtitle = title_text
  ) +
  theme(
    plot.title.position = 'plot',
    text = element_text(color = 'grey20'),
    axis.text = element_text(color = 'grey30'),
    plot.title = element_text(family = 'Merriweather', size = 26, margin = margin(b = 7, unit = 'mm')),
    plot.subtitle = ggtext::element_markdown(size = 18, lineheight = 1.3),
    panel.background = element_rect(color = 'grey90'),
    panel.grid.major = element_line(color = 'grey90'),
    panel.grid.minor = element_blank(),
    legend.position = 'none'
  )
```

```{r}
setwd(here::here('39_Aug_02_2023'))
ggsave(
  'exported_plot.png',
  width = 6,
  height = 6 * 9 / 16,
  bg = 'white'
)
```

```{r}
camcorder::gg_record(
  dir = 'imgs',
  width = 12,
  height = 12 * 9 / 16,
  dpi = 300,
  bg = 'white' 
  # Makes sure background of plot is actually white, not transparent
)
```
